# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: nlxio/gemma-ztc
    environment:
      - DJANGO_SETTINGS_MODULE=ztc.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
  tests:
    build:
      context: ./
      target: jenkins
    volumes:
      - ${WORKSPACE}/reports:/app/reports
    environment:
      - DJANGO_SETTINGS_MODULE=ztc.conf.jenkins
      - SECRET_KEY=jenkins
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_HOST=db
    depends_on:
      - db

volumes:
  postgres_data:
