# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres
  web:
    image: vngr/gemma-ztc
    environment:
      - DJANGO_SETTINGS_MODULE=ztc.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
